/**:
  ros__parameters:
    # plugins
    plugins_path: $(find-pkg-share autoware_tensorrt_plugins)/plugins/libautoware_tensorrt_plugins.so
    # network
    trt_precision: fp16
    cloud_capacity: 2000000
    encoder:
      onnx_path: "$(var model_path)/$(var model_variant)_encoder.onnx"
      engine_path: "$(var model_path)/$(var model_variant)_encoder.engine"
      workspace_size: 8589934592  # 8 GiB
      voxels_num: [16000, 160000, 256000]
    segmentation3d:
      use_head: $(var use_seg3d_head)
      onnx_path: "$(var model_path)/$(var model_variant)_seg3d_head.onnx"
      engine_path: "$(var model_path)/$(var model_variant)_seg3d_head.engine"
      workspace_size: 8589934592  # 8 GiB
      source_reconstruction: "full"
      # Mapping from segmentation3d.class_names to autoware::point_types::PointCloudClassification.
      class_mapping:
        car: CAR
        truck: TRUCK
        bus: BUS
        bicycle: BICYCLE
        pedestrian: PEDESTRIAN
        traffic_cone: HAZARD
        debris: HAZARD
        vertical_thin: HAZARD
        barrier: STRUCTURE
        building: STRUCTURE
        static_clutter: STRUCTURE
        drivable_flat: FLAT_SURFACE
        non_drivable_flat: FLAT_SURFACE
        vegetation: VEGETATION
        noise: NOISE
      filter:
        classes: ["drivable_flat", "non_drivable_flat", "noise"]
        output_format: ""
        apply_to_segmentation: false
    detection3d:
      use_head: $(var use_det3d_head)
      onnx_path: "$(var model_path)/$(var model_variant)_det3d_head.onnx"
      engine_path: "$(var model_path)/$(var model_variant)_det3d_head.engine"
      workspace_size: 4294967296  # 4 GiB
      post_process_params:
        iou_nms_search_distance_2d: 10.0
        iou_nms_threshold: 0.1
        yaw_norm_thresholds: [0.1, 0.1, 0.1, 0.1, 0.0, 0.0, 0.1]
      detection_score_thresholds:
        distance_bin_upper_limits: [50.0, 90.0, 121.0, 200.0]
        min_confidence_scores:
          CAR: [0.1, 0.1, 0.1, 0.1]
          TRUCK: [0.1, 0.1, 0.1, 0.1]
          BUS: [0.1, 0.1, 0.1, 0.1]
          BICYCLE: [0.1, 0.1, 0.1, 0.1]
          PEDESTRIAN: [0.1, 0.1, 0.1, 0.1]
          TRAFFIC_CONE: [0.1, 0.1, 0.1, 0.1]
          BARRIER: [0.1, 0.1, 0.1, 0.1]
      allow_remapping_by_area_matrix:
        # Row: original class. Column: class to remap to.
        # CAR, TRUCK, BUS, BICYCLE, PEDESTRIAN, TRAFFIC_CONE, BARRIER
        [0,    1,    0,   0,       0,           0,            0,        # CAR
        0,    0,    0,   0,       0,           0,            0,        # TRUCK
        0,    0,    0,   0,       0,           0,            0,        # BUS
        0,    0,    0,   0,       0,           0,            0,        # BICYCLE
        0,    0,    0,   0,       0,           0,            0,        # PEDESTRIAN
        0,    0,    0,   0,       0,           0,            0,        # TRAFFIC_CONE
        0,    0,    0,   0,       0,           0,            0]        # BARRIER
      min_area_matrix:
        # CAR,    TRUCK,  BUS,   BICYCLE, PEDESTRIAN, TRAFFIC_CONE, BARRIER
        [0.000,  12.100,  0.000, 0.000,   0.000,      0.000,        0.000,    # CAR
        0.000,   0.000,  0.000, 0.000,   0.000,      0.000,        0.000,    # TRUCK
        0.000,   0.000,  0.000, 0.000,   0.000,      0.000,        0.000,    # BUS
        0.000,   0.000,  0.000, 0.000,   0.000,      0.000,        0.000,    # BICYCLE
        0.000,   0.000,  0.000, 0.000,   0.000,      0.000,        0.000,    # PEDESTRIAN
        0.000,   0.000,  0.000, 0.000,   0.000,      0.000,        0.000,    # TRAFFIC_CONE
        0.000,   0.000,  0.000, 0.000,   0.000,      0.000,        0.000]    # BARRIER
      max_area_matrix:
        # CAR,    TRUCK,   BUS,   BICYCLE, PEDESTRIAN, TRAFFIC_CONE, BARRIER
        [0.000,  36.000,  0.000,  0.000,   0.000,      0.000,        0.000,    # CAR
        0.000,   0.000,  0.000,  0.000,   0.000,      0.000,        0.000,    # TRUCK
        0.000,   0.000,  0.000,  0.000,   0.000,      0.000,        0.000,    # BUS
        0.000,   0.000,  0.000,  0.000,   0.000,      0.000,        0.000,    # BICYCLE
        0.000,   0.000,  0.000,  0.000,   0.000,      0.000,        0.000,    # PEDESTRIAN
        0.000,   0.000,  0.000,  0.000,   0.000,      0.000,        0.000,    # TRAFFIC_CONE
        0.000,   0.000,  0.000,  0.000,   0.000,      0.000,        0.000]    # BARRIER
