/**:
  ros__parameters:
    boundary_departure_prevention:
      th_data_timeout_s: 1.0
      boundary_types_to_detect: [road_border]
      th_max_lateral_query_num: 5

      abnormality:
        normal: true
        localization: true
        longitudinal: true
        steering: false

      slow_down_near_boundary:
        enable: true
        th_trigger:
          decel_mp2: -1.0
          brake_delay_s: 1.3
          dist_error_m: 0.25
        th_dist_to_boundary_m:
          left: 0.5
          right: 0.5
        slow_down_behavior:
          velocity_kmh: 10.0

      slow_down_before_departure:
        enable: true
        th_trigger:
          decel_mp2: -1.0
          brake_delay_s: 1.3
          dist_error_m: 0.25
        th_dist_to_boundary_m:
          left: 0.001
          right: 0.001

      stop_before_departure:
        enable: true
        th_trigger:
          decel_mp2: -1.0
          brake_delay_s: 1.3
          dist_error_m: 0.25
        th_dist_to_boundary_m:
          left: 0.001
          right: 0.001

      predicted_path_footprint:
        scale: 1.0
        extra_margin_m: 0.0
        resample_interval_m: 0.3

      footprint_envelop:
        lon_m: 0.25
        lat_m: 0.25

      lon_tracking:
        scale: 1.0
        extra_margin_m: 0.0
