/**:
  ros__parameters:
    boundary_departure_prevention:
      th_data_timeout_s: 1.0
      boundary_types_to_detect: [road_border]

      slow_down_near_boundary:
        enable: true
        th_dist_to_boundary_m:
          left: 0.25
          right: 0.25

      slow_down_before_departure:
        enable: true
        th_dist_to_boundary_m:
          left: 0.001
          right: 0.001

      stop_before_departure:
        enable: true
        th_dist_to_boundary_m:
          left: 0.001
          right: 0.001

      predicted_path_footprint:
        scale: 1.0
        extra_margin_m: 0.0
        resample_interval_m: 0.3
